apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/hoodie-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: PAYMENT_URL
              value: "http://payment:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
    - port: 8080
      targetPort: 8080
